### ISSUE TITLE
smart ring with buttons and LED

### ISSUE THREAD

**Issue by x3e** [atc1441/ATC_RF03_Ring#1]
When searching for a place to buy this, I came across a slightly different smart ring that has capacitive touch points and an outward-facing led (at least in the product video) Do you think the SoC wil be the same?

https://www.aliexpress.com/item/1005007176784654.html

A downside of this one is that the epoxy layer on the inside is not transparent and I wonder if it will be possible to wire up the swd like you did.

Anyway, I ordered one and if you want I 'll report back once I have received it.

**Comment by atc1441** [comment]
Hey, 

that ring looks like it is just emulating a mouse. There is a chance that the firmware in it will be fixed.

It seems its missing any additional features like Accl or Heartrate sensor.
Still interesting.

Looking forward to a report from you with hopefully a name of the chip used :) 

![Unbenannt](https://github.com/atc1441/ATC_RF03_Ring/assets/1102694/71c77efe-b958-459c-92b0-e3cf75abd6a0)

**Comment by x3e** [comment]
Seems like this ring is quite different. It has a different construction as well, with the metal ring being on the inside and not on the outside of the ring. Disassembly seems easier, although I probably broke a trace when peeling off the PCB (heating the glue might help).

Sadly, the IC is different. I couldn't get a good photograph of the marking, but it is a JL IC marked with something like "BPOP203-23A2". Couldn't find any info on it.

If you want, you can close this issue as it doesn't seem to be related to your work on the other ring.

![IMG_20240702_171450](https://github.com/atc1441/ATC_RF03_Ring/assets/33860364/8cbb78ca-d0d2-495f-b8f6-e8ac7663aedc)
![IMG_20240702_171843](https://github.com/atc1441/ATC_RF03_Ring/assets/33860364/d422ad39-9e5c-420e-b03f-3467e56e8d96)
![IMG_20240703_092617](https://github.com/atc1441/ATC_RF03_Ring/assets/33860364/2fcb7bcf-b79e-40b1-ac8e-16a37d485adc)

**Comment by atc1441** [comment]
Thank you for the insights of the ring,

The SoC is this one: https://www.lcsc.com/product-detail/Microcontroller-Units-MCUs-MPUs-SOCs_JieLi-Tech-AC6323A4_C5440136.html

Quite capable but with a bad sleep current. There would be an SDK but as you mention its a different Project overall.
