### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Sakd99** [atc1441/ATC_RF03_Ring#11]
I want to get my web files
https://atc1441.github.io/ATC_RF03_Writer.html
To localize the website, I need it for my graduation project, please

**Comment by Sakd99** [comment]
@atc1441

**Comment by Sakd99** [comment]
i got that

**Comment by Utopiah** [comment]
How did you get it though? Just downloading the page?

The code itself is relatively readible as-it but it would still be great to have it in this repository if one wants to discuss it, improve it, etc and of course a clear license.
