### ISSUE TITLE
OTA Firmware Flashing Tool Connect issue

### ISSUE THREAD

**Issue by skaken** [atc1441/ATC_RF03_Ring#6]
I have problems connecting to a R02 ring and can’t seem to figure out what the problem is. I have tried several browsers(Chrome, Edge, Firefox) and devices(IOS and windows) but I don’t get to choose any devices after pressing connect.

**Comment by Ken-76** [comment]
Did some reading on WebBluetooth, and it isn’t supported on IOS(Chrome, Safari and Firefox at least). Doesn’t explain why it isn’t supported on Windows but I’ll have to look into it a bit deeper, or dig out an Android unit/try Linux.
